### ISSUE TITLE
scitools only works with python 2

### ISSUE THREAD

**Issue by kaymmm** [GCDigitalFellows/drbdotfiles#1]
We have a few options:
1. install everything in system via python 2 and forget about 3
2. install everything in both 2+3 except scitools only in 2
3. don't install anything as system (except maybe numpy and matplotlib) and make people install stuff as user or using virtualenv
4. other ideas???

i'm inclined to suggest installing everything in system (via pyenv) in both 2+3, then make people wanting to use scitools either set up a virtualenv or switch the "global" python to python 2 via pyenv.

**Comment by story645** [comment]
3:
a) It's fairly straighforward to teach people about anaconda envs (I vote for using them over pyenv/virtualenv since we're using anaconda) if we just fold it into the beggining of our python lesson
b) we'll know which libraries we're teaching, so we could in theory install those as global 
c) honestly, I'm with you on installing them as an env-anaconda has a really simple way to share environments and I like the idea of keeping the system pythons super clean
d) pip has a great --user tool
4. Ignore scitools. This is gonna sound obnoxious, but never heard of scitools before now and my quick review of it is that I'm not a fan 'cause it seems to obfuscate a lot of stuff that's gonna bite people later. It's mostly thin wrappers on matplotlib and scipy.

**Comment by kaymmm** [comment]
lol i only included scitools because i thought you had requested it for the last drb. it's gone from the list.

see my comment in basecamp regarding 3.

also, with pyenv, nothing is install "globally" since i have pyenv set up to install in user. however, i could switch that via user profile to use a single global pyenv in /usr/local/opt/pyenv or wherever, so that things like numpy and matplotlib would just work without having to worry about virtualenvs or user installs.

**Comment by smythp** [comment]
pyenv is awesome, and you can use it to install anaconda. I second pyenv.

$ pyenv install anaconda3-2.5.0

Patrick

Patrick

**Comment by story645** [comment]
Ok fine, pyenv, but just to install 3 since it seems like we won't need 2 anymore. (or will we do 2 just to be on the safe side?) and then default on the student accounts is anaconda 3.

So I still suggest making an [anaconda environment file](http://conda.pydata.org/docs/using/envs.html) and then just creating them from bash and having bash maybe auto activate that environment: conda env create -f environment.yml
Or yeah, use pyenv to just install everything in the student. I still think we should keep global python clean since we don't know what else we'll use these for.

**Comment by kaymmm** [comment]
the scripts currently install anaconda3 using pyenv and sets anaconda as the default python. the user script should also set the anaconda virtualenv whenever a terminal is opened.
